// Generated from data/KGpo11.json. Do not edit this file manually.
export const DEFAULT_SEASON = {
  "schemaVersion": 1,
  "season": 2026,
  "seriesName": "Puchar Polski Strongman Tyberian Team",
  "maxCountedStarts": 4,
  "pointsByPosition": {
    "1": 5,
    "2": 4,
    "3": 3,
    "4": 2,
    "5": 1
  },
  "updatedThrough": "2026-08-09",
  "events": [
    {
      "id": "season-2026-01",
      "number": 1,
      "date": "2026-05-01",
      "location": "Siewierz",
      "name": "Siewierz · 01.05.2026",
      "sourceFile": "SIEWIERZ 1.05.2026",
      "ranking": [
        {
          "position": 1,
          "competitorId": "competitor-lukasz-kieliszkowski",
          "name": "Łukasz Kieliszkowski",
          "sourceName": "ŁUKASZ KIELISZKOWSKI",
          "seasonPoints": 5,
          "competitionPoints": 23
        },
        {
          "position": 2,
          "competitorId": "competitor-marcin-stankiewicz",
          "name": "Marcin Stankiewicz",
          "sourceName": "MARCIN STANKIEWICZ",
          "seasonPoints": 4,
          "competitionPoints": 20
        },
        {
          "position": 3,
          "competitorId": "competitor-bartlomiej-babol",
          "name": "Bartłomiej Bąbol",
          "sourceName": "BARTŁOMIEJ BĄBOL",
          "seasonPoints": 3,
          "competitionPoints": 19
        },
        {
          "position": 4,
          "competitorId": "competitor-bartosz-postoj",
          "name": "Bartosz Postój",
          "sourceName": "BARTŁOMIEJ POSYÓJ (i) Wygrana przez: więcej 2. miejsc",
          "seasonPoints": 2,
          "competitionPoints": 11
        },
        {
          "position": 5,
          "competitorId": "competitor-krzysztof-kacnerski",
          "name": "Krzysztof Kacnerski",
          "sourceName": "KRZYSZTOF KACNERSKI",
          "seasonPoints": 1,
          "competitionPoints": 11
        }
      ],
      "competitions": [
        {
          "id": "event-spacer-farmera-140-kg-2-x-20-m",
          "name": "Spacer Farmera 140 kg - 2 x 20 m",
          "type": "low",
          "final": false,
          "sourceName": "Spacer Farmera na czas 140 kg 2x20m"
        },
        {
          "id": "event-wyciskanie-belki-140-kg-60-sek",
          "name": "Wyciskanie belki 140 kg - 60 sek.",
          "type": "high",
          "final": false,
          "sourceName": "Wyciskanie belki 140 kg"
        },
        {
          "id": "event-uchwyt-herkulesa",
          "name": "Uchwyt Herkulesa",
          "type": "high",
          "final": false,
          "sourceName": "Uchwyt Herkulesa"
        },
        {
          "id": "event-spacer-buszmena-380-kg-20-m",
          "name": "Spacer Buszmena 380 kg - 20 m",
          "type": "low",
          "final": false,
          "sourceName": "Spacer Buszmena 380 kg"
        },
        {
          "id": "event-worki-zaladunek-3-x-100-kg",
          "name": "Worki - załadunek 3 x 100 kg",
          "type": "low",
          "final": false,
          "sourceName": "Worki 3x100 kg"
        },
        {
          "id": "event-przerzucanie-opony-360-kg-6-obrotow",
          "name": "Przerzucanie opony 360 kg - 6 obrotów",
          "type": "low",
          "final": true,
          "sourceName": "Przerzucanie opony 360 hg"
        }
      ]
    },
    {
      "id": "season-2026-02",
      "number": 2,
      "date": "2026-05-30",
      "location": "Czerwonak",
      "name": "Czerwonak · 30.05.2026",
      "sourceFile": "Czerwonak 30.05",
      "ranking": [
        {
          "position": 1,
          "competitorId": "competitor-jakub-szczechowski",
          "name": "Jakub Szczechowski",
          "sourceName": "JAKUB SZCZECHOWSKI",
          "seasonPoints": 5,
          "competitionPoints": 24
        },
        {
          "position": 2,
          "competitorId": "competitor-marcin-schabowski",
          "name": "Marcin Schabowski",
          "sourceName": "MARCIN SCHABOWSKI",
          "seasonPoints": 4,
          "competitionPoints": 22
        },
        {
          "position": 3,
          "competitorId": "competitor-tomasz-lademann",
          "name": "Tomasz Lademann",
          "sourceName": "TOMASZ LADEMANN",
          "seasonPoints": 3,
          "competitionPoints": 20
        },
        {
          "position": 4,
          "competitorId": "competitor-pawel-kostrzewski",
          "name": "Paweł Kostrzewski",
          "sourceName": "PAWEL KOSTRZEWSKI",
          "seasonPoints": 2,
          "competitionPoints": 13
        },
        {
          "position": 5,
          "competitorId": "competitor-mariusz-pachut",
          "name": "Mariusz Pachut",
          "sourceName": "MARIUSZ PACHUT",
          "seasonPoints": 1,
          "competitionPoints": 11
        }
      ],
      "competitions": [
        {
          "id": "event-spacer-farmera-140-kg-2-x-20-m",
          "name": "Spacer Farmera 140 kg - 2 x 20 m",
          "type": "low",
          "final": false,
          "sourceName": "Spacer Farmera 140 kg - 2 x 20m"
        },
        {
          "id": "event-wyciskanie-belki-140-kg-60-sek",
          "name": "Wyciskanie belki 140 kg - 60 sek.",
          "type": "high",
          "final": false,
          "sourceName": "Wyciskanie belki 140 kg - 60 sek"
        },
        {
          "id": "event-przerzucanie-workow-nad-poprzeczka-20-30-kg",
          "name": "Przerzucanie worków nad poprzeczką - 20-30 kg",
          "type": "low",
          "final": false,
          "sourceName": "Worki - przerzucanie nad poprzeczka - 20, 22, 24, 26, 28, 30 kg"
        },
        {
          "id": "event-worki-zaladunek-3-x-100-kg",
          "name": "Worki - załadunek 3 x 100 kg",
          "type": "low",
          "final": false,
          "sourceName": "Worki - zaladunek 3 x 100 kg"
        },
        {
          "id": "event-przerzucanie-opony-360-kg-6-obrotow",
          "name": "Przerzucanie opony 360 kg - 6 obrotów",
          "type": "low",
          "final": false,
          "sourceName": "Przerzucanie opony 360 kg - 6 obrotow"
        },
        {
          "id": "event-uchwyt-herkulesa",
          "name": "Uchwyt Herkulesa",
          "type": "high",
          "final": true,
          "sourceName": "Uchwyt Herkulesa"
        }
      ]
    },
    {
      "id": "season-2026-03",
      "number": 3,
      "date": "2026-06-01",
      "location": "Kleszczów",
      "name": "Kleszczów · 01.06.2026",
      "sourceFile": "Kleszczów 1.06",
      "ranking": [
        {
          "position": 1,
          "competitorId": "competitor-lukasz-kieliszkowski",
          "name": "Łukasz Kieliszkowski",
          "sourceName": "LUKASZ KIELISZKOWSKI",
          "seasonPoints": 5,
          "competitionPoints": 24.5
        },
        {
          "position": 2,
          "competitorId": "competitor-rafal-sojc",
          "name": "Rafał Sojc",
          "sourceName": "RAFAL SOJC",
          "seasonPoints": 4,
          "competitionPoints": 20.5
        },
        {
          "position": 3,
          "competitorId": "competitor-bartlomiej-babol",
          "name": "Bartłomiej Bąbol",
          "sourceName": "BARTLOMIEJ BABOL",
          "seasonPoints": 3,
          "competitionPoints": 17.5
        },
        {
          "position": 4,
          "competitorId": "competitor-bartosz-postoj",
          "name": "Bartosz Postój",
          "sourceName": "BARTOSZ POSTOJ",
          "seasonPoints": 2,
          "competitionPoints": 15.5
        },
        {
          "position": 5,
          "competitorId": "competitor-pawel-piskorz",
          "name": "Paweł Piskorz",
          "sourceName": "PAWEL PISKORZ",
          "seasonPoints": 1,
          "competitionPoints": 12
        }
      ],
      "competitions": [
        {
          "id": "event-spacer-farmera-140-kg-2-x-20-m",
          "name": "Spacer Farmera 140 kg - 2 x 20 m",
          "type": "low",
          "final": false,
          "sourceName": "Spacer Farmera 140 kg - 2 x 20m"
        },
        {
          "id": "event-przerzucanie-workow-nad-poprzeczka-20-30-kg",
          "name": "Przerzucanie worków nad poprzeczką - 20-30 kg",
          "type": "low",
          "final": false,
          "sourceName": "Worki - przerzucanie nad poprzeczka - 20, 22, 24, 26, 28, 30 kg"
        },
        {
          "id": "event-wyciskanie-belki-140-kg-60-sek",
          "name": "Wyciskanie belki 140 kg - 60 sek.",
          "type": "high",
          "final": false,
          "sourceName": "Wyciskanie belki 140 kg - 60 sek"
        },
        {
          "id": "event-laczona-worki-kowadlo",
          "name": "Łączona: worki + kowadło",
          "type": "low",
          "final": false,
          "sourceName": "Laczona: worki + kowadlo"
        },
        {
          "id": "event-przerzucanie-opony-360-kg-6-obrotow",
          "name": "Przerzucanie opony 360 kg - 6 obrotów",
          "type": "low",
          "final": false,
          "sourceName": "Przerzucanie opony 360 kg - 6 obrotow"
        },
        {
          "id": "event-martwy-ciag-powtorzenia",
          "name": "Martwy ciąg (powtórzenia)",
          "type": "high",
          "final": true,
          "sourceName": "Martwy ciag (powtorzenia)"
        }
      ]
    },
    {
      "id": "season-2026-04",
      "number": 4,
      "date": "2026-06-06",
      "location": "Ruciane-Nida",
      "name": "Ruciane-Nida · 06.06.2026",
      "sourceFile": "Ruciane-Nida 06.06.2026 r",
      "ranking": [
        {
          "position": 1,
          "competitorId": "competitor-rafal-sojc",
          "name": "Rafał Sojc",
          "sourceName": "RAFAL SOJC",
          "seasonPoints": 5,
          "competitionPoints": 25
        },
        {
          "position": 2,
          "competitorId": "competitor-pawel-piskorz",
          "name": "Paweł Piskorz",
          "sourceName": "PAWEL PISKORZ",
          "seasonPoints": 4,
          "competitionPoints": 21
        },
        {
          "position": 3,
          "competitorId": "competitor-marcin-stankiewicz",
          "name": "Marcin Stankiewicz",
          "sourceName": "MARCIN STANKIEWICZ",
          "seasonPoints": 3,
          "competitionPoints": 19
        },
        {
          "position": 4,
          "competitorId": "competitor-przemyslaw-marczewski",
          "name": "Przemysław Marczewski",
          "sourceName": "PRZEMYSLAW MARCZEWSKI",
          "seasonPoints": 2,
          "competitionPoints": 15
        },
        {
          "position": 5,
          "competitorId": "competitor-mariusz-pachut",
          "name": "Mariusz Pachut",
          "sourceName": "MARIUSZ PACHUT",
          "seasonPoints": 1,
          "competitionPoints": 6
        }
      ],
      "competitions": [
        {
          "id": "event-spacer-farmera-140-kg-na-dystans",
          "name": "Spacer Farmera 140 kg - na dystans",
          "type": "high",
          "final": false,
          "sourceName": "Spacer Farmera 140 kg - 2 x 20m"
        },
        {
          "id": "event-zegar",
          "name": "Zegar",
          "type": "high",
          "final": false,
          "sourceName": "Zegar"
        },
        {
          "id": "event-axel-gryf-130-kg-60-sek",
          "name": "Axel Gryf 130 kg - 60 sek.",
          "type": "high",
          "final": false,
          "sourceName": "Axel Gryf 130 kg. X 60 sek"
        },
        {
          "id": "event-spacer-buszmena-380-kg-20-m",
          "name": "Spacer Buszmena 380 kg - 20 m",
          "type": "low",
          "final": false,
          "sourceName": "Spacer Buszmena 380 kg. x 20m"
        },
        {
          "id": "event-przeciaganie-auta-w-siadzie",
          "name": "Przeciąganie auta w siadzie",
          "type": "low",
          "final": false,
          "sourceName": "Przeciaganie auta w siadzie"
        },
        {
          "id": "event-przerzucanie-kuli-przez-yoke-140-kg-60-sek",
          "name": "Przerzucanie kuli przez Yoke - 140 kg, 60 sek.",
          "type": "high",
          "final": true,
          "sourceName": "Przerzucanie kuli przez Yoke - 140 kg x 60 sek"
        }
      ]
    },
    {
      "id": "season-2026-05",
      "number": 5,
      "date": "2026-06-07",
      "location": "Prabuty",
      "name": "Prabuty · 07.06.2026",
      "sourceFile": "Prabuty 07.06.2026 r",
      "ranking": [
        {
          "position": 1,
          "competitorId": "competitor-lukasz-kieliszkowski",
          "name": "Łukasz Kieliszkowski",
          "sourceName": "LUKASZ KIELISZKOWSKI",
          "seasonPoints": 5,
          "competitionPoints": 25
        },
        {
          "position": 2,
          "competitorId": "competitor-jakub-szczechowski",
          "name": "Jakub Szczechowski",
          "sourceName": "JAKUB SZCZECHOWSKI",
          "seasonPoints": 4,
          "competitionPoints": 23
        },
        {
          "position": 3,
          "competitorId": "competitor-bartlomiej-babol",
          "name": "Bartłomiej Bąbol",
          "sourceName": "BARTLOMIEJ BABOL",
          "seasonPoints": 3,
          "competitionPoints": 18.5
        },
        {
          "position": 4,
          "competitorId": "competitor-pawel-kostrzewski",
          "name": "Paweł Kostrzewski",
          "sourceName": "PAWEL KOSTRZEWSKI",
          "seasonPoints": 2,
          "competitionPoints": 15
        },
        {
          "position": 5,
          "competitorId": "competitor-krzysztof-kacnerski",
          "name": "Krzysztof Kacnerski",
          "sourceName": "KRZYSZTOF KACNERSKI",
          "seasonPoints": 1,
          "competitionPoints": 7.5
        }
      ],
      "competitions": [
        {
          "id": "event-spacer-farmera-140-kg-na-dystans",
          "name": "Spacer Farmera 140 kg - na dystans",
          "type": "high",
          "final": false,
          "sourceName": "Spacer Farmera na dystans 140 kg"
        },
        {
          "id": "event-zegar",
          "name": "Zegar",
          "type": "high",
          "final": false,
          "sourceName": "Zegar"
        },
        {
          "id": "event-przerzucanie-workow-nad-poprzeczka-20-30-kg",
          "name": "Przerzucanie worków nad poprzeczką - 20-30 kg",
          "type": "low",
          "final": false,
          "sourceName": "Worki - przerzucanie nad poprzeczka - 20, 22, 24, 26, 28, 30 kg"
        },
        {
          "id": "event-laczona-barkowa-belka-140-kg-axel-130-kg-i-hantel-90-kg",
          "name": "Łączona barkowa: belka 140 kg, Axel 130 kg i hantel 90 kg",
          "type": "low",
          "final": false,
          "sourceName": "Laczona Barkowa: Belka 140, Axel 130 i Hantel 90kg"
        },
        {
          "id": "event-przerzucanie-kuli-przez-yoke-140-kg-60-sek",
          "name": "Przerzucanie kuli przez Yoke - 140 kg, 60 sek.",
          "type": "high",
          "final": false,
          "sourceName": "Przerzucanie kuli przez Yoke - 140 kg x 60 sek"
        },
        {
          "id": "event-przeciaganie-auta-w-siadzie",
          "name": "Przeciąganie auta w siadzie",
          "type": "low",
          "final": true,
          "sourceName": "Przeciaganie auta w siadzie"
        }
      ]
    },
    {
      "id": "season-2026-06",
      "number": 6,
      "date": "2026-06-12",
      "location": "Tuszyn",
      "name": "Tuszyn · 12.06.2026",
      "sourceFile": "Tuszyn 12.06.2026 r",
      "ranking": [
        {
          "position": 1,
          "competitorId": "competitor-pawel-piskorz",
          "name": "Paweł Piskorz",
          "sourceName": "PAWEL PISKORZ",
          "seasonPoints": 5,
          "competitionPoints": 21
        },
        {
          "position": 2,
          "competitorId": "competitor-bartosz-postoj",
          "name": "Bartosz Postój",
          "sourceName": "BARTOSZ POSTOJ",
          "seasonPoints": 4,
          "competitionPoints": 19
        },
        {
          "position": 3,
          "competitorId": "competitor-lukasz-kieliszkowski",
          "name": "Łukasz Kieliszkowski",
          "sourceName": "LUKASZ KIELISZKOWSKI",
          "seasonPoints": 3,
          "competitionPoints": 18.5
        },
        {
          "position": 4,
          "competitorId": "competitor-bartlomiej-babol",
          "name": "Bartłomiej Bąbol",
          "sourceName": "BARTLOMIEJ BABOL",
          "seasonPoints": 2,
          "competitionPoints": 17
        },
        {
          "position": 5,
          "competitorId": "competitor-adam-wadolowski",
          "name": "Adam Wądołowski",
          "sourceName": "ADAM WADOLOWSKI",
          "seasonPoints": 1,
          "competitionPoints": 14.5
        }
      ],
      "competitions": [
        {
          "id": "event-wyciskanie-platformy-na-barki",
          "name": "Wyciskanie platformy na barki",
          "type": "high",
          "final": false,
          "sourceName": "Wyciskanie Platformy na barki"
        },
        {
          "id": "event-przerzucanie-workow-nad-poprzeczka-20-30-kg",
          "name": "Przerzucanie worków nad poprzeczką - 20-30 kg",
          "type": "low",
          "final": false,
          "sourceName": "Worki - przerzucanie nad poprzeczka - 20, 22, 24, 26, 28, 30 kg"
        },
        {
          "id": "event-laczona-worki-kowadlo",
          "name": "Łączona: worki + kowadło",
          "type": "low",
          "final": false,
          "sourceName": "Laczona: worki + kowadlo"
        },
        {
          "id": "event-nosidlo-300-kg-2-x-20-m",
          "name": "Nosidło 300 kg - 2 x 20 m",
          "type": "low",
          "final": false,
          "sourceName": "NOSIDLO 300 kg - 2 x 20m"
        },
        {
          "id": "event-spacer-buszmena-380-kg-20-m",
          "name": "Spacer Buszmena 380 kg - 20 m",
          "type": "low",
          "final": false,
          "sourceName": "Spacer Buszmena 380 kg. x 20m"
        },
        {
          "id": "event-tir-w-siadzie",
          "name": "Tir w siadzie",
          "type": "low",
          "final": true,
          "sourceName": "Tir w siadzie"
        }
      ]
    },
    {
      "id": "season-2026-07",
      "number": 7,
      "date": "2026-06-27",
      "location": "Busko-Zdrój",
      "name": "Busko-Zdrój · 27.06.2026",
      "sourceFile": "Busko-Zdroj 27.06.2026 r",
      "ranking": [
        {
          "position": 1,
          "competitorId": "competitor-rafal-sojc",
          "name": "Rafał Sojc",
          "sourceName": "RAFAL SOJC",
          "seasonPoints": 5,
          "competitionPoints": 24.5
        },
        {
          "position": 2,
          "competitorId": "competitor-bartlomiej-babol",
          "name": "Bartłomiej Bąbol",
          "sourceName": "BARTLOMIEJ BABOL",
          "seasonPoints": 4,
          "competitionPoints": 19.5
        },
        {
          "position": 3,
          "competitorId": "competitor-marcin-stankiewicz",
          "name": "Marcin Stankiewicz",
          "sourceName": "MARCIN STANKIEWICZ",
          "seasonPoints": 3,
          "competitionPoints": 19.5
        },
        {
          "position": 4,
          "competitorId": "competitor-bartosz-postoj",
          "name": "Bartosz Postój",
          "sourceName": "BARTOSZ POSTOJ",
          "seasonPoints": 2,
          "competitionPoints": 15.5
        },
        {
          "position": 5,
          "competitorId": "competitor-michal-maruszewski",
          "name": "Michał Maruszewski",
          "sourceName": "MICHAL MARUSZEWSKI",
          "seasonPoints": 1,
          "competitionPoints": 11
        }
      ],
      "competitions": [
        {
          "id": "event-spacer-farmera-140-kg-na-dystans",
          "name": "Spacer Farmera 140 kg - na dystans",
          "type": "high",
          "final": false,
          "sourceName": "Spacer Farmera na dystans 140 kg"
        },
        {
          "id": "event-wyciskanie-belki-140-kg-60-sek",
          "name": "Wyciskanie belki 140 kg - 60 sek.",
          "type": "high",
          "final": false,
          "sourceName": "Wyciskanie belki 140 kg - 60 sek"
        },
        {
          "id": "event-przerzucanie-opony-360-kg-6-obrotow",
          "name": "Przerzucanie opony 360 kg - 6 obrotów",
          "type": "low",
          "final": false,
          "sourceName": "Przerzucanie opony 360 kg. x 6 obrotow"
        },
        {
          "id": "event-spacer-buszmena-380-kg-20-m",
          "name": "Spacer Buszmena 380 kg - 20 m",
          "type": "low",
          "final": false,
          "sourceName": "Spacer Buszmena 380 kg - 20m"
        },
        {
          "id": "event-przeciaganie-lodzi-w-siadzie",
          "name": "Przeciąganie łodzi w siadzie",
          "type": "low",
          "final": false,
          "sourceName": "Przeciaganie LODZI w siadzie"
        },
        {
          "id": "event-przeciaganie-auta-w-siadzie",
          "name": "Przeciąganie auta w siadzie",
          "type": "low",
          "final": true,
          "sourceName": "Przeciaganie auta w siadzie"
        }
      ]
    },
    {
      "id": "season-2026-08",
      "number": 8,
      "date": "2026-07-25",
      "location": "Kleczew",
      "name": "Kleczew · 25.07.2026",
      "sourceFile": "KLECZEW · 26.07.2026",
      "ranking": [
        {
          "position": 1,
          "competitorId": "competitor-pawel-piskorz",
          "name": "Paweł Piskorz",
          "sourceName": "PAWEŁ PISKORZ",
          "seasonPoints": 5,
          "competitionPoints": 23
        },
        {
          "position": 2,
          "competitorId": "competitor-marcin-stankiewicz",
          "name": "Marcin Stankiewicz",
          "sourceName": "MARCIN STANKIEWICZ",
          "seasonPoints": 4,
          "competitionPoints": 19
        },
        {
          "position": 3,
          "competitorId": "competitor-pawel-kostrzewski",
          "name": "Paweł Kostrzewski",
          "sourceName": "PAWEŁ KOSTRZEWSKI",
          "seasonPoints": 3,
          "competitionPoints": 17.5
        },
        {
          "position": 4,
          "competitorId": "competitor-adam-wadolowski",
          "name": "Adam Wądołowski",
          "sourceName": "ADAM WĄDOŁOWSKI",
          "seasonPoints": 2,
          "competitionPoints": 16
        },
        {
          "position": 5,
          "competitorId": "competitor-krzysztof-kacnerski",
          "name": "Krzysztof Kacnerski",
          "sourceName": "KRZYSZTOF KACNERSKI",
          "seasonPoints": 1,
          "competitionPoints": 14.5
        }
      ],
      "competitions": [
        {
          "id": "event-spacer-farmera-na-dystans",
          "name": "Spacer Farmera na dystans",
          "type": "high",
          "final": false,
          "sourceName": "Spacer Farmera na dystans"
        },
        {
          "id": "event-spacer-buszmena-380-kg-20-m",
          "name": "Spacer Buszmena 380 kg - 20 m",
          "type": "low",
          "final": false,
          "sourceName": "Spacer Buszmena 380 kg - 20m"
        },
        {
          "id": "event-wyciskanie-belki-140-kg-60-sek",
          "name": "Wyciskanie belki 140 kg - 60 sek.",
          "type": "high",
          "final": false,
          "sourceName": "Wyciskanie belki 140 kg - 60 sek"
        },
        {
          "id": "event-kegi-x-6-przerzucanie-nad-poprzeczka",
          "name": "Kegi x 6 - przerzucanie nad poprzeczką",
          "type": "low",
          "final": false,
          "sourceName": "KEGI x 6 nad poprzeczką"
        },
        {
          "id": "event-zegar",
          "name": "Zegar",
          "type": "high",
          "final": false,
          "sourceName": "Zegar"
        },
        {
          "id": "event-uchwyt-herkulesa",
          "name": "Uchwyt Herkulesa",
          "type": "high",
          "final": true,
          "sourceName": "Uchwyt Herkulesa"
        }
      ]
    },
    {
      "id": "season-2026-09",
      "number": 9,
      "date": "2026-07-26",
      "location": "Lubawka",
      "name": "Lubawka · 26.07.2026",
      "sourceFile": "LUBAWKA · 26.07.2026",
      "ranking": [
        {
          "position": 1,
          "competitorId": "competitor-pawel-piskorz",
          "name": "Paweł Piskorz",
          "sourceName": "PAWEŁ PISKORZ",
          "seasonPoints": 5,
          "competitionPoints": 26
        },
        {
          "position": 2,
          "competitorId": "competitor-rafal-sojc",
          "name": "Rafał Sojc",
          "sourceName": "RAFAŁ SOJC",
          "seasonPoints": 4,
          "competitionPoints": 21
        },
        {
          "position": 3,
          "competitorId": "competitor-pawel-kostrzewski",
          "name": "Paweł Kostrzewski",
          "sourceName": "PAWEŁ KOSTRZEWSKI",
          "seasonPoints": 3,
          "competitionPoints": 18
        },
        {
          "position": 4,
          "competitorId": "competitor-bartosz-postoj",
          "name": "Bartosz Postój",
          "sourceName": "BARTOSZ POSTÓJ",
          "seasonPoints": 2,
          "competitionPoints": 16
        },
        {
          "position": 5,
          "competitorId": "competitor-mariusz-pachut",
          "name": "Mariusz Pachut",
          "sourceName": "MARIUSZ PACHUT",
          "seasonPoints": 1,
          "competitionPoints": 9
        }
      ],
      "competitions": [
        {
          "id": "event-spacer-farmera-140-kg-2-x-20-m",
          "name": "Spacer Farmera 140 kg - 2 x 20 m",
          "type": "low",
          "final": false,
          "sourceName": "Spacer Farmera na czas 140 kg 2x20m"
        },
        {
          "id": "event-worki-zaladunek-3-x-100-kg",
          "name": "Worki - załadunek 3 x 100 kg",
          "type": "low",
          "final": false,
          "sourceName": "Worki - załadunek 3 x 100 kg"
        },
        {
          "id": "event-wyciskanie-belek-140-150-i-160-kg",
          "name": "Wyciskanie belek 140, 150 i 160 kg",
          "type": "low",
          "final": false,
          "sourceName": "Wyciskanie Belek 3 x 140, 150, 160 kg"
        },
        {
          "id": "event-kegi-x-6-przerzucanie-nad-poprzeczka",
          "name": "Kegi x 6 - przerzucanie nad poprzeczką",
          "type": "low",
          "final": false,
          "sourceName": "KEGI x 6 - PRZERZUCANIE"
        },
        {
          "id": "event-zegar",
          "name": "Zegar",
          "type": "high",
          "final": false,
          "sourceName": "Zegar"
        },
        {
          "id": "event-uchwyt-herkulesa",
          "name": "Uchwyt Herkulesa",
          "type": "high",
          "final": true,
          "sourceName": "Uchwyt Herkulesa"
        }
      ]
    },
    {
      "id": "season-2026-10",
      "number": 10,
      "date": "2026-08-02",
      "location": "Radwanice",
      "name": "Radwanice · 02.08.2026",
      "sourceFile": "RADWANICE 2.08.2026 r",
      "ranking": [
        {
          "position": 1,
          "competitorId": "competitor-jakub-szczechowski",
          "name": "Jakub Szczechowski",
          "sourceName": "JAKUB SZCZECHOWSKI",
          "seasonPoints": 5,
          "competitionPoints": 28
        },
        {
          "position": 2,
          "competitorId": "competitor-pawel-kostrzewski",
          "name": "Paweł Kostrzewski",
          "sourceName": "PAWEŁ KOSTRZEWSKI",
          "seasonPoints": 4,
          "competitionPoints": 21
        },
        {
          "position": 3,
          "competitorId": "competitor-pawel-piskorz",
          "name": "Paweł Piskorz",
          "sourceName": "PAWEŁ PISKORZ",
          "seasonPoints": 3,
          "competitionPoints": 16
        },
        {
          "position": 4,
          "competitorId": "competitor-krzysztof-kacnerski",
          "name": "Krzysztof Kacnerski",
          "sourceName": "KRZYSZTOF KACNERSKI",
          "seasonPoints": 2,
          "competitionPoints": 15
        },
        {
          "position": 5,
          "competitorId": "competitor-mariusz-pachut",
          "name": "Mariusz Pachut",
          "sourceName": "MARIUSZ PACHUT",
          "seasonPoints": 1,
          "competitionPoints": 6
        }
      ],
      "competitions": [
        {
          "id": "event-spacer-farmera-140-kg-2-x-20-m",
          "name": "Spacer Farmera 140 kg - 2 x 20 m",
          "type": "low",
          "final": false,
          "sourceName": "Spacer Farmera na czas 140 kg 2x20m"
        },
        {
          "id": "event-przerzucanie-workow-nad-poprzeczka-20-30-kg",
          "name": "Przerzucanie worków nad poprzeczką - 20-30 kg",
          "type": "low",
          "final": false,
          "sourceName": "Worki - przerzucanie nad poprzeczką - 20, 22, 24, 26, 28, 30 kg"
        },
        {
          "id": "event-wyciskanie-belki-140-kg-60-sek",
          "name": "Wyciskanie belki 140 kg - 60 sek.",
          "type": "high",
          "final": false,
          "sourceName": "Wyciskanie belki 140 kg - 60 sek"
        },
        {
          "id": "event-przerzucanie-opony-360-kg-8-obrotow",
          "name": "Przerzucanie opony 360 kg - 8 obrotów",
          "type": "low",
          "final": false,
          "sourceName": "Przerzucanie opony 360 kg x 8 obrotów"
        },
        {
          "id": "event-przeciaganie-auta",
          "name": "Przeciąganie auta",
          "type": "low",
          "final": false,
          "sourceName": "Przeciąganie Auta"
        },
        {
          "id": "event-martwy-ciag-na-platformie",
          "name": "Martwy ciąg na platformie",
          "type": "high",
          "final": true,
          "sourceName": "Martwy ciąg na Platformie"
        }
      ]
    },
    {
      "id": "season-2026-11",
      "number": 11,
      "date": "2026-08-09",
      "location": "Skalbmierz",
      "name": "Skalbmierz · 09.08.2026",
      "sourceFile": "Podsumowanie Skalbmierz 09.08.2026 (HTML)",
      "ranking": [
        {
          "position": 1,
          "competitorId": "competitor-marcin-stankiewicz",
          "name": "Marcin Stankiewicz",
          "sourceName": "MARCIN STANKIEWICZ",
          "seasonPoints": 5,
          "competitionPoints": 25
        },
        {
          "position": 2,
          "competitorId": "competitor-tomasz-lademann",
          "name": "Tomasz Lademann",
          "sourceName": "TOMASZ LADEMANN",
          "seasonPoints": 4,
          "competitionPoints": 23.5
        },
        {
          "position": 3,
          "competitorId": "competitor-bartosz-postoj",
          "name": "Bartosz Postój",
          "sourceName": "BARTOSZ POSTÓJ",
          "seasonPoints": 3,
          "competitionPoints": 19.5
        },
        {
          "position": 4,
          "competitorId": "competitor-michal-sajdak-1786279130885-bf0b79",
          "name": "Michał Sajdak",
          "sourceName": "MICHAŁ SAJDAK",
          "seasonPoints": 2,
          "competitionPoints": 15
        },
        {
          "position": 5,
          "competitorId": "competitor-michal-maruszewski",
          "name": "Michał Maruszewski",
          "sourceName": "MICHAŁ MARUSZEWSKI",
          "seasonPoints": 1,
          "competitionPoints": 7
        }
      ],
      "competitions": [
        {
          "id": "event-spacer-farmera-140-kg-2-x-20-m",
          "name": "Spacer Farmera 140 kg - 2 x 20 m",
          "type": "low",
          "final": false,
          "sourceName": "Spacer Farmera na czas 140 kg 2x20m",
          "results": [
            {
              "position": 1,
              "competitorId": "competitor-marcin-stankiewicz",
              "name": "Marcin Stankiewicz",
              "sourceName": "MARCIN STANKIEWICZ",
              "result": "20.45",
              "points": 5
            },
            {
              "position": 2,
              "competitorId": "competitor-tomasz-lademann",
              "name": "Tomasz Lademann",
              "sourceName": "TOMASZ LADEMANN",
              "result": "21.67",
              "points": 4
            },
            {
              "position": 3,
              "competitorId": "competitor-michal-sajdak-1786279130885-bf0b79",
              "name": "Michał Sajdak",
              "sourceName": "MICHAŁ SAJDAK",
              "result": "22.59",
              "points": 3
            },
            {
              "position": 4,
              "competitorId": "competitor-bartosz-postoj",
              "name": "Bartosz Postój",
              "sourceName": "BARTOSZ POSTÓJ",
              "result": "23.63",
              "points": 2
            },
            {
              "position": 5,
              "competitorId": "competitor-michal-maruszewski",
              "name": "Michał Maruszewski",
              "sourceName": "MICHAŁ MARUSZEWSKI",
              "result": "24.32",
              "points": 1
            }
          ]
        },
        {
          "id": "event-spacer-buszmena-360-kg-20-m-zaladunek",
          "name": "Spacer Buszmena 360 kg - 20 m + załadunek",
          "type": "low",
          "final": false,
          "sourceName": "Spacer Buszmena 360 kg - 20m + załadunek 3 worki",
          "results": [
            {
              "position": 1,
              "competitorId": "competitor-marcin-stankiewicz",
              "name": "Marcin Stankiewicz",
              "sourceName": "MARCIN STANKIEWICZ",
              "result": "41.",
              "points": 5
            },
            {
              "position": 2,
              "competitorId": "competitor-tomasz-lademann",
              "name": "Tomasz Lademann",
              "sourceName": "TOMASZ LADEMANN",
              "result": "54.83",
              "points": 4
            },
            {
              "position": 3,
              "competitorId": "competitor-bartosz-postoj",
              "name": "Bartosz Postój",
              "sourceName": "BARTOSZ POSTÓJ",
              "result": "60.26",
              "points": 3
            },
            {
              "position": 4,
              "competitorId": "competitor-michal-sajdak-1786279130885-bf0b79",
              "name": "Michał Sajdak",
              "sourceName": "MICHAŁ SAJDAK",
              "result": "83.38",
              "points": 2
            },
            {
              "position": 5,
              "competitorId": "competitor-michal-maruszewski",
              "name": "Michał Maruszewski",
              "sourceName": "MICHAŁ MARUSZEWSKI",
              "result": "99",
              "points": 1
            }
          ]
        },
        {
          "id": "event-przeciaganie-auta",
          "name": "Przeciąganie auta",
          "type": "low",
          "final": false,
          "sourceName": "Przeciąganie auta",
          "results": [
            {
              "position": 1,
              "competitorId": "competitor-tomasz-lademann",
              "name": "Tomasz Lademann",
              "sourceName": "TOMASZ LADEMANN",
              "result": "13.75",
              "points": 5
            },
            {
              "position": 2,
              "competitorId": "competitor-bartosz-postoj",
              "name": "Bartosz Postój",
              "sourceName": "BARTOSZ POSTÓJ",
              "result": "14.38",
              "points": 4
            },
            {
              "position": 3,
              "competitorId": "competitor-michal-sajdak-1786279130885-bf0b79",
              "name": "Michał Sajdak",
              "sourceName": "MICHAŁ SAJDAK",
              "result": "15.26",
              "points": 3
            },
            {
              "position": 4,
              "competitorId": "competitor-marcin-stankiewicz",
              "name": "Marcin Stankiewicz",
              "sourceName": "MARCIN STANKIEWICZ",
              "result": "15.81",
              "points": 2
            },
            {
              "position": 5,
              "competitorId": "competitor-michal-maruszewski",
              "name": "Michał Maruszewski",
              "sourceName": "MICHAŁ MARUSZEWSKI",
              "result": "16.75",
              "points": 1
            }
          ]
        },
        {
          "id": "event-wyciskanie-platformy-na-barki",
          "name": "Wyciskanie platformy na barki",
          "type": "high",
          "final": false,
          "sourceName": "Wyciskanie platformy na barki - 60 sek.",
          "results": [
            {
              "position": 1,
              "competitorId": "competitor-bartosz-postoj",
              "name": "Bartosz Postój",
              "sourceName": "BARTOSZ POSTÓJ",
              "result": "9",
              "points": 4.5
            },
            {
              "position": 1,
              "competitorId": "competitor-tomasz-lademann",
              "name": "Tomasz Lademann",
              "sourceName": "TOMASZ LADEMANN",
              "result": "9",
              "points": 4.5
            },
            {
              "position": 3,
              "competitorId": "competitor-marcin-stankiewicz",
              "name": "Marcin Stankiewicz",
              "sourceName": "MARCIN STANKIEWICZ",
              "result": "5",
              "points": 3
            },
            {
              "position": 4,
              "competitorId": "competitor-michal-maruszewski",
              "name": "Michał Maruszewski",
              "sourceName": "MICHAŁ MARUSZEWSKI",
              "result": "3",
              "points": 2
            },
            {
              "position": 5,
              "competitorId": "competitor-michal-sajdak-1786279130885-bf0b79",
              "name": "Michał Sajdak",
              "sourceName": "MICHAŁ SAJDAK",
              "result": "1",
              "points": 1
            }
          ]
        },
        {
          "id": "event-przerzucanie-workow-nad-poprzeczka-20-30-kg",
          "name": "Przerzucanie worków nad poprzeczką - 20-30 kg",
          "type": "low",
          "final": false,
          "sourceName": "Przerzucanie worków nad poprzeczką",
          "results": [
            {
              "position": 1,
              "competitorId": "competitor-marcin-stankiewicz",
              "name": "Marcin Stankiewicz",
              "sourceName": "MARCIN STANKIEWICZ",
              "result": "14.75",
              "points": 5
            },
            {
              "position": 2,
              "competitorId": "competitor-bartosz-postoj",
              "name": "Bartosz Postój",
              "sourceName": "BARTOSZ POSTÓJ",
              "result": "19.78",
              "points": 4
            },
            {
              "position": 3,
              "competitorId": "competitor-michal-sajdak-1786279130885-bf0b79",
              "name": "Michał Sajdak",
              "sourceName": "MICHAŁ SAJDAK",
              "result": "30.94",
              "points": 3
            },
            {
              "position": 4,
              "competitorId": "competitor-tomasz-lademann",
              "name": "Tomasz Lademann",
              "sourceName": "TOMASZ LADEMANN",
              "result": "38.26",
              "points": 2
            },
            {
              "position": 5,
              "competitorId": "competitor-michal-maruszewski",
              "name": "Michał Maruszewski",
              "sourceName": "MICHAŁ MARUSZEWSKI",
              "result": "212.54",
              "points": 1
            }
          ]
        },
        {
          "id": "event-martwy-ciag-powtorzenia",
          "name": "Martwy ciąg (powtórzenia)",
          "type": "high",
          "final": true,
          "sourceName": "Martwy ciąg (powtórzenia) - boczny chwyt. (FINAŁ)",
          "results": [
            {
              "position": 1,
              "competitorId": "competitor-marcin-stankiewicz",
              "name": "Marcin Stankiewicz",
              "sourceName": "MARCIN STANKIEWICZ",
              "result": "19",
              "points": 5
            },
            {
              "position": 2,
              "competitorId": "competitor-tomasz-lademann",
              "name": "Tomasz Lademann",
              "sourceName": "TOMASZ LADEMANN",
              "result": "18",
              "points": 4
            },
            {
              "position": 3,
              "competitorId": "competitor-michal-sajdak-1786279130885-bf0b79",
              "name": "Michał Sajdak",
              "sourceName": "MICHAŁ SAJDAK",
              "result": "16",
              "points": 3
            },
            {
              "position": 4,
              "competitorId": "competitor-bartosz-postoj",
              "name": "Bartosz Postój",
              "sourceName": "BARTOSZ POSTÓJ",
              "result": "12",
              "points": 2
            },
            {
              "position": 5,
              "competitorId": "competitor-michal-maruszewski",
              "name": "Michał Maruszewski",
              "sourceName": "MICHAŁ MARUSZEWSKI",
              "result": "7",
              "points": 1
            }
          ]
        }
      ]
    }
  ],
  "standings": [
    {
      "competitorId": "competitor-pawel-piskorz",
      "name": "Paweł Piskorz",
      "results": [
        {
          "eventId": "season-2026-03",
          "eventNumber": 3,
          "date": "2026-06-01",
          "location": "Kleszczów",
          "position": 5,
          "points": 1
        },
        {
          "eventId": "season-2026-04",
          "eventNumber": 4,
          "date": "2026-06-06",
          "location": "Ruciane-Nida",
          "position": 2,
          "points": 4
        },
        {
          "eventId": "season-2026-06",
          "eventNumber": 6,
          "date": "2026-06-12",
          "location": "Tuszyn",
          "position": 1,
          "points": 5
        },
        {
          "eventId": "season-2026-08",
          "eventNumber": 8,
          "date": "2026-07-25",
          "location": "Kleczew",
          "position": 1,
          "points": 5
        },
        {
          "eventId": "season-2026-09",
          "eventNumber": 9,
          "date": "2026-07-26",
          "location": "Lubawka",
          "position": 1,
          "points": 5
        },
        {
          "eventId": "season-2026-10",
          "eventNumber": 10,
          "date": "2026-08-02",
          "location": "Radwanice",
          "position": 3,
          "points": 3
        }
      ],
      "starts": 6,
      "countedEventIds": [
        "season-2026-06",
        "season-2026-08",
        "season-2026-09",
        "season-2026-04"
      ],
      "allPoints": 23,
      "countedPoints": 19,
      "rejectedPoints": 4,
      "rank": 1
    },
    {
      "competitorId": "competitor-lukasz-kieliszkowski",
      "name": "Łukasz Kieliszkowski",
      "results": [
        {
          "eventId": "season-2026-01",
          "eventNumber": 1,
          "date": "2026-05-01",
          "location": "Siewierz",
          "position": 1,
          "points": 5
        },
        {
          "eventId": "season-2026-03",
          "eventNumber": 3,
          "date": "2026-06-01",
          "location": "Kleszczów",
          "position": 1,
          "points": 5
        },
        {
          "eventId": "season-2026-05",
          "eventNumber": 5,
          "date": "2026-06-07",
          "location": "Prabuty",
          "position": 1,
          "points": 5
        },
        {
          "eventId": "season-2026-06",
          "eventNumber": 6,
          "date": "2026-06-12",
          "location": "Tuszyn",
          "position": 3,
          "points": 3
        }
      ],
      "starts": 4,
      "countedEventIds": [
        "season-2026-01",
        "season-2026-03",
        "season-2026-05",
        "season-2026-06"
      ],
      "allPoints": 18,
      "countedPoints": 18,
      "rejectedPoints": 0,
      "rank": 2
    },
    {
      "competitorId": "competitor-rafal-sojc",
      "name": "Rafał Sojc",
      "results": [
        {
          "eventId": "season-2026-03",
          "eventNumber": 3,
          "date": "2026-06-01",
          "location": "Kleszczów",
          "position": 2,
          "points": 4
        },
        {
          "eventId": "season-2026-04",
          "eventNumber": 4,
          "date": "2026-06-06",
          "location": "Ruciane-Nida",
          "position": 1,
          "points": 5
        },
        {
          "eventId": "season-2026-07",
          "eventNumber": 7,
          "date": "2026-06-27",
          "location": "Busko-Zdrój",
          "position": 1,
          "points": 5
        },
        {
          "eventId": "season-2026-09",
          "eventNumber": 9,
          "date": "2026-07-26",
          "location": "Lubawka",
          "position": 2,
          "points": 4
        }
      ],
      "starts": 4,
      "countedEventIds": [
        "season-2026-04",
        "season-2026-07",
        "season-2026-03",
        "season-2026-09"
      ],
      "allPoints": 18,
      "countedPoints": 18,
      "rejectedPoints": 0,
      "rank": 2
    },
    {
      "competitorId": "competitor-marcin-stankiewicz",
      "name": "Marcin Stankiewicz",
      "results": [
        {
          "eventId": "season-2026-01",
          "eventNumber": 1,
          "date": "2026-05-01",
          "location": "Siewierz",
          "position": 2,
          "points": 4
        },
        {
          "eventId": "season-2026-04",
          "eventNumber": 4,
          "date": "2026-06-06",
          "location": "Ruciane-Nida",
          "position": 3,
          "points": 3
        },
        {
          "eventId": "season-2026-07",
          "eventNumber": 7,
          "date": "2026-06-27",
          "location": "Busko-Zdrój",
          "position": 3,
          "points": 3
        },
        {
          "eventId": "season-2026-08",
          "eventNumber": 8,
          "date": "2026-07-25",
          "location": "Kleczew",
          "position": 2,
          "points": 4
        },
        {
          "eventId": "season-2026-11",
          "eventNumber": 11,
          "date": "2026-08-09",
          "location": "Skalbmierz",
          "position": 1,
          "points": 5
        }
      ],
      "starts": 5,
      "countedEventIds": [
        "season-2026-11",
        "season-2026-01",
        "season-2026-08",
        "season-2026-04"
      ],
      "allPoints": 19,
      "countedPoints": 16,
      "rejectedPoints": 3,
      "rank": 4
    },
    {
      "competitorId": "competitor-jakub-szczechowski",
      "name": "Jakub Szczechowski",
      "results": [
        {
          "eventId": "season-2026-02",
          "eventNumber": 2,
          "date": "2026-05-30",
          "location": "Czerwonak",
          "position": 1,
          "points": 5
        },
        {
          "eventId": "season-2026-05",
          "eventNumber": 5,
          "date": "2026-06-07",
          "location": "Prabuty",
          "position": 2,
          "points": 4
        },
        {
          "eventId": "season-2026-10",
          "eventNumber": 10,
          "date": "2026-08-02",
          "location": "Radwanice",
          "position": 1,
          "points": 5
        }
      ],
      "starts": 3,
      "countedEventIds": [
        "season-2026-02",
        "season-2026-10",
        "season-2026-05"
      ],
      "allPoints": 14,
      "countedPoints": 14,
      "rejectedPoints": 0,
      "rank": 5
    },
    {
      "competitorId": "competitor-bartlomiej-babol",
      "name": "Bartłomiej Bąbol",
      "results": [
        {
          "eventId": "season-2026-01",
          "eventNumber": 1,
          "date": "2026-05-01",
          "location": "Siewierz",
          "position": 3,
          "points": 3
        },
        {
          "eventId": "season-2026-03",
          "eventNumber": 3,
          "date": "2026-06-01",
          "location": "Kleszczów",
          "position": 3,
          "points": 3
        },
        {
          "eventId": "season-2026-05",
          "eventNumber": 5,
          "date": "2026-06-07",
          "location": "Prabuty",
          "position": 3,
          "points": 3
        },
        {
          "eventId": "season-2026-06",
          "eventNumber": 6,
          "date": "2026-06-12",
          "location": "Tuszyn",
          "position": 4,
          "points": 2
        },
        {
          "eventId": "season-2026-07",
          "eventNumber": 7,
          "date": "2026-06-27",
          "location": "Busko-Zdrój",
          "position": 2,
          "points": 4
        }
      ],
      "starts": 5,
      "countedEventIds": [
        "season-2026-07",
        "season-2026-01",
        "season-2026-03",
        "season-2026-05"
      ],
      "allPoints": 15,
      "countedPoints": 13,
      "rejectedPoints": 2,
      "rank": 6
    },
    {
      "competitorId": "competitor-pawel-kostrzewski",
      "name": "Paweł Kostrzewski",
      "results": [
        {
          "eventId": "season-2026-02",
          "eventNumber": 2,
          "date": "2026-05-30",
          "location": "Czerwonak",
          "position": 4,
          "points": 2
        },
        {
          "eventId": "season-2026-05",
          "eventNumber": 5,
          "date": "2026-06-07",
          "location": "Prabuty",
          "position": 4,
          "points": 2
        },
        {
          "eventId": "season-2026-08",
          "eventNumber": 8,
          "date": "2026-07-25",
          "location": "Kleczew",
          "position": 3,
          "points": 3
        },
        {
          "eventId": "season-2026-09",
          "eventNumber": 9,
          "date": "2026-07-26",
          "location": "Lubawka",
          "position": 3,
          "points": 3
        },
        {
          "eventId": "season-2026-10",
          "eventNumber": 10,
          "date": "2026-08-02",
          "location": "Radwanice",
          "position": 2,
          "points": 4
        }
      ],
      "starts": 5,
      "countedEventIds": [
        "season-2026-10",
        "season-2026-08",
        "season-2026-09",
        "season-2026-02"
      ],
      "allPoints": 14,
      "countedPoints": 12,
      "rejectedPoints": 2,
      "rank": 7
    },
    {
      "competitorId": "competitor-bartosz-postoj",
      "name": "Bartosz Postój",
      "results": [
        {
          "eventId": "season-2026-01",
          "eventNumber": 1,
          "date": "2026-05-01",
          "location": "Siewierz",
          "position": 4,
          "points": 2
        },
        {
          "eventId": "season-2026-03",
          "eventNumber": 3,
          "date": "2026-06-01",
          "location": "Kleszczów",
          "position": 4,
          "points": 2
        },
        {
          "eventId": "season-2026-06",
          "eventNumber": 6,
          "date": "2026-06-12",
          "location": "Tuszyn",
          "position": 2,
          "points": 4
        },
        {
          "eventId": "season-2026-07",
          "eventNumber": 7,
          "date": "2026-06-27",
          "location": "Busko-Zdrój",
          "position": 4,
          "points": 2
        },
        {
          "eventId": "season-2026-09",
          "eventNumber": 9,
          "date": "2026-07-26",
          "location": "Lubawka",
          "position": 4,
          "points": 2
        },
        {
          "eventId": "season-2026-11",
          "eventNumber": 11,
          "date": "2026-08-09",
          "location": "Skalbmierz",
          "position": 3,
          "points": 3
        }
      ],
      "starts": 6,
      "countedEventIds": [
        "season-2026-06",
        "season-2026-11",
        "season-2026-01",
        "season-2026-03"
      ],
      "allPoints": 15,
      "countedPoints": 11,
      "rejectedPoints": 4,
      "rank": 8
    },
    {
      "competitorId": "competitor-tomasz-lademann",
      "name": "Tomasz Lademann",
      "results": [
        {
          "eventId": "season-2026-02",
          "eventNumber": 2,
          "date": "2026-05-30",
          "location": "Czerwonak",
          "position": 3,
          "points": 3
        },
        {
          "eventId": "season-2026-11",
          "eventNumber": 11,
          "date": "2026-08-09",
          "location": "Skalbmierz",
          "position": 2,
          "points": 4
        }
      ],
      "starts": 2,
      "countedEventIds": [
        "season-2026-11",
        "season-2026-02"
      ],
      "allPoints": 7,
      "countedPoints": 7,
      "rejectedPoints": 0,
      "rank": 9
    },
    {
      "competitorId": "competitor-krzysztof-kacnerski",
      "name": "Krzysztof Kacnerski",
      "results": [
        {
          "eventId": "season-2026-01",
          "eventNumber": 1,
          "date": "2026-05-01",
          "location": "Siewierz",
          "position": 5,
          "points": 1
        },
        {
          "eventId": "season-2026-05",
          "eventNumber": 5,
          "date": "2026-06-07",
          "location": "Prabuty",
          "position": 5,
          "points": 1
        },
        {
          "eventId": "season-2026-08",
          "eventNumber": 8,
          "date": "2026-07-25",
          "location": "Kleczew",
          "position": 5,
          "points": 1
        },
        {
          "eventId": "season-2026-10",
          "eventNumber": 10,
          "date": "2026-08-02",
          "location": "Radwanice",
          "position": 4,
          "points": 2
        }
      ],
      "starts": 4,
      "countedEventIds": [
        "season-2026-10",
        "season-2026-01",
        "season-2026-05",
        "season-2026-08"
      ],
      "allPoints": 5,
      "countedPoints": 5,
      "rejectedPoints": 0,
      "rank": 10
    },
    {
      "competitorId": "competitor-marcin-schabowski",
      "name": "Marcin Schabowski",
      "results": [
        {
          "eventId": "season-2026-02",
          "eventNumber": 2,
          "date": "2026-05-30",
          "location": "Czerwonak",
          "position": 2,
          "points": 4
        }
      ],
      "starts": 1,
      "countedEventIds": [
        "season-2026-02"
      ],
      "allPoints": 4,
      "countedPoints": 4,
      "rejectedPoints": 0,
      "rank": 11
    },
    {
      "competitorId": "competitor-mariusz-pachut",
      "name": "Mariusz Pachut",
      "results": [
        {
          "eventId": "season-2026-02",
          "eventNumber": 2,
          "date": "2026-05-30",
          "location": "Czerwonak",
          "position": 5,
          "points": 1
        },
        {
          "eventId": "season-2026-04",
          "eventNumber": 4,
          "date": "2026-06-06",
          "location": "Ruciane-Nida",
          "position": 5,
          "points": 1
        },
        {
          "eventId": "season-2026-09",
          "eventNumber": 9,
          "date": "2026-07-26",
          "location": "Lubawka",
          "position": 5,
          "points": 1
        },
        {
          "eventId": "season-2026-10",
          "eventNumber": 10,
          "date": "2026-08-02",
          "location": "Radwanice",
          "position": 5,
          "points": 1
        }
      ],
      "starts": 4,
      "countedEventIds": [
        "season-2026-02",
        "season-2026-04",
        "season-2026-09",
        "season-2026-10"
      ],
      "allPoints": 4,
      "countedPoints": 4,
      "rejectedPoints": 0,
      "rank": 11
    },
    {
      "competitorId": "competitor-adam-wadolowski",
      "name": "Adam Wądołowski",
      "results": [
        {
          "eventId": "season-2026-06",
          "eventNumber": 6,
          "date": "2026-06-12",
          "location": "Tuszyn",
          "position": 5,
          "points": 1
        },
        {
          "eventId": "season-2026-08",
          "eventNumber": 8,
          "date": "2026-07-25",
          "location": "Kleczew",
          "position": 4,
          "points": 2
        }
      ],
      "starts": 2,
      "countedEventIds": [
        "season-2026-08",
        "season-2026-06"
      ],
      "allPoints": 3,
      "countedPoints": 3,
      "rejectedPoints": 0,
      "rank": 13
    },
    {
      "competitorId": "competitor-michal-maruszewski",
      "name": "Michał Maruszewski",
      "results": [
        {
          "eventId": "season-2026-07",
          "eventNumber": 7,
          "date": "2026-06-27",
          "location": "Busko-Zdrój",
          "position": 5,
          "points": 1
        },
        {
          "eventId": "season-2026-11",
          "eventNumber": 11,
          "date": "2026-08-09",
          "location": "Skalbmierz",
          "position": 5,
          "points": 1
        }
      ],
      "starts": 2,
      "countedEventIds": [
        "season-2026-07",
        "season-2026-11"
      ],
      "allPoints": 2,
      "countedPoints": 2,
      "rejectedPoints": 0,
      "rank": 14
    },
    {
      "competitorId": "competitor-michal-sajdak-1786279130885-bf0b79",
      "name": "Michał Sajdak",
      "results": [
        {
          "eventId": "season-2026-11",
          "eventNumber": 11,
          "date": "2026-08-09",
          "location": "Skalbmierz",
          "position": 4,
          "points": 2
        }
      ],
      "starts": 1,
      "countedEventIds": [
        "season-2026-11"
      ],
      "allPoints": 2,
      "countedPoints": 2,
      "rejectedPoints": 0,
      "rank": 14
    },
    {
      "competitorId": "competitor-przemyslaw-marczewski",
      "name": "Przemysław Marczewski",
      "results": [
        {
          "eventId": "season-2026-04",
          "eventNumber": 4,
          "date": "2026-06-06",
          "location": "Ruciane-Nida",
          "position": 4,
          "points": 2
        }
      ],
      "starts": 1,
      "countedEventIds": [
        "season-2026-04"
      ],
      "allPoints": 2,
      "countedPoints": 2,
      "rejectedPoints": 0,
      "rank": 14
    }
  ]
};
